language: cpp
sudo: required
compiler:
- gcc
before_install:
- sudo apt-get install libnetfilter-log-dev
- sudo apt-get install libgtest-dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
script:
- cd /home/travis/build/jameshloving/edict/test
- cmake CMakeLists.txt
- make
- ./runTests
notifications:
    email: false
